### PR TITLE
Add my soul octocat (Issue #1)

### PR DESCRIPTION
**Pull request by rukshankr**
I have added my soul OctoCat files into codebase (Issue #1 ).

### CODE REVIEW

**Comment by buddhikac96** [comment]
Great work! Totally mergeable. Could you write a much descriptive and clean PR message:)?

Suggestions:
- [x] - Mention the issue in the title (#1)
- [x] - First letter capital ;)
- [x] - Please mention complete files names instead .md file and .png

**Comment by rukshankr** [comment]
> Great work! Totally mergeable. Could you write a much descriptive and clean PR message:)?
> 
> Suggestions:
> 
> * [x]  - Mention the issue in the title (#1)
> * [x]  - First letter capital ;)
> * [x]  - Please mention complete files names instead .md file and .png

Thank you, I changed the PR description. Hope that it's correct.

**Comment by Yasas4D** [comment]
yah. now it's looking really nice!

**Comment by buddhikac96** [comment]
That's nice. Thank you for the code!

**Pull request merged**
